---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  "Template to launch an ec2 from CF"
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-04a0ae173da5807d3"
      InstanceType: t2.micro
      SecurityGroupIds: 
        - "sg-0846a2567e343c677"
      SubnetId: subnet-0128647c9f2a75a4d 
      KeyName: "lab-key-pem"
      Tags: 
        - Key: "Name"
          Value: "myEC2Instance"
      # trust the process