---
# we are workong on parameters with an EC2 
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0ff8a91507f77f867"
      InstanceType: 
        !Ref InstanceTypeYollan
      SubnetId: subnet-0ff28d65d8d43bf94

Parameters:
  InstanceTypeYollan:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro. 
  myKeyPair: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"

  # mySubnetIDs: 
  #   Description: Subnet IDs
  #   Type: "AWS::EC2::Subnet::Id"